* Shownotes
  In this episode of Pain Points & Pull Requests, Fatimah and Carla discuss their takeaways from Cal Newport's book, "Deep Work". They begin by unpacking what it means to work effectively, given their continuously evolving contexts and goals.
  They then break down Cal Newport's main points in "Deep Work" about what effective work looks likes, the lifestyle choices that can hinder this kind of work, and how we can better support deep work habits in our lives.
  Check out this episode to learn all about deep work and whether it's time for you to make space for it in your life

** Things you'll learn
*** 00:56 Why should we think about how we work? 
*** 02:28 What does it mean to work effectively?
*** 5:46 What is deep work all about?
*** 10:09 Attention Residue
*** 17:40 How we tailor our productivity systems
*** 20:26 How to modify your productivity system based on your context
*** 36:29 Why deep work may not be the only answer

** Resources Mentioned
*** Sophie Leroy Research
    https://www.chieflearningofficer.com/2018/03/02/conquering-attention-residue/
*** Deep Work book
    https://www.amazon.ca/Deep-Work-Focused-Success-Distracted/dp/1455586692/ref=sr_1_1?crid=1UWNUJZ8HOK04&keywords=deep+work&qid=1579647194&sprefix=deep+wotk%2Caps%2C283&sr=8-1
*** Cal Newport blog
    https://www.calnewport.com/blog/
*** A complete guide to deep work
    https://doist.com/blog/complete-guide-to-deep-work/
*** Matt D'Avella Deep Work
    https://www.youtube.com/watch?v=kRr9LQ7mZ_A&t=17s
