Welcome to Episode 2 - All About Theranos. In this episode of Pain Points and Pull Requests Fatimah and Carla discuss the demise of a 9 billion dollar startup.

Elizabeth Holmes dropped out of Stanford at age 19 to found the med-tech company Theranos. Her success story was one that the world watched, as she revolutionized blood testing for millions and was named the youngest 
female self-made billionaire. Theranos no longer exists today and Elizabeth is set to go on trial for massive fraud in July. Listen to this episode of Pain Points and Pull Requests to find out more about the downfall of Theranos.

** Things you'll learn
1. 2:00 The Story of Theranos & Elizabeth Holmes
2. 4:50 The Optimistic Entrepreneur
3. 14:40 Managing your users' expectations
4. 20:53 Staying in a company that isn't ethical

    
** Find out more about Elizabeth Holmes and Theranos:
*** Theranos movie
*** The Dropout - Podcast by ABC
*** HBO Documentary “The Inventor”
*** Wall Street Journal Article by John Carryrou
