In this episode of Pain Points & Pull Requests, Fatimah and Carla discuss the significance methods of achieving project sustainability.

As co-op students we want to emphasize the importance of work that can be transitioned easily. A sustainable project is one that has requirements, 
functionality and code that is easy to understand and built upon. By developing projects that are sustainable, we decrease the  barriers that prevent
others from helping us solve problems. Often these barriers come in the form of messy code, poorly documented functionality, and hard to follow programs.
Join Fatimah and Carla in unpacking what it means to build a project that is sustainable and understanding the tools and techniques that can be used to
achieve sustainability.

* Things you'll learn
** 1:24 Why should we think about project sustainability?
** 4:34 What are the characteristics of a sustainable project?
** 5:42 Sustainability of a project from the business perspective
** 11:48 What to include in a user guide
** 16:02 Documenting your code for other developers
** 22:06 Testing
** 30:14 Code Style
* Resources Mentioned
** A beginner's guide to writing documentation https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/
** The Pragmatic Programmer https://www.amazon.ca/s?k=pragmatic+programmer&ref=nb_sb_noss_2
** Sphinx Tutorial https://www.youtube.com/watch?v=qrcj7sVuvUA
** Programming Throwdown Podcast: https://www.programmingthrowdown.com/
** Code formatter for Visual Studio Code https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
** Flake 8 https://pypi.org/project/flake8/
** Black https://pypi.org/project/black/
** Creating a pre-commit https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
** What is Regression Testing? https://www.guru99.com/regression-testing.html
