* Shownotes
In this episodes of Pain Points & Pull Requests, Fatimah and Carla walk you through their approach to analyzing data to validate a hypothesis. When we approach mid-February, we often find that our new
year's resolutions have begun to dwindle. In an effort to understand how long people usually stick to their new year's resolutions, Fatimah and Carla perform an analysis on Canadian cigarette
consumption time-series data. Check out this episode to learn more about the data analysis techniques and tools that they used!
** What you'll learn
*** 2:00 The quantified self movement
*** 4:02 How we found data to answer our question
*** 8:02 How we cleaned our data
*** 12:04 How we explored our data
*** 14:10 Our findings
** Extra Resources
*** Google Datasets
    https://datasetsearch.research.google.com/
*** Open Data
    https://open.canada.ca/en/open-data
*** Open Refine
    https://openrefine.org/
*** Anaconda
    https://www.anaconda.com/
*** How to handle missing data
    https://medium.com/coinmonks/dealing-with-missing-data-using-r-3ae428da2d17
