* Show Notes
In this episode of Pain Points and Pull Requests Fatimah and Carla discuss open source software. Open source software is made up of code that is freely available for the public to inspect, study, copy and repurpose. 

Over the past two decades releasing software projects with open source licenses has become widely accepted and common. Some incredibly useful and fascinating tools have been releasedas open source projects 
like Microsoft Visual Studio, Python and Spareslab (the image processing library used to take the first picture of a black hole!). Contributing to open source software is also a great way for developers to
gain collaboration experience on projects. Fatimah and Carla will take you through the steps to contribute to open source software and the tools that you can use to make that process less intimidating. Enjoy!

** Things you'll learn
*** 1:22 What is Open Source Software?
*** 1:44 What are examples of open source projects? Why do companies open source their projects?
*** 6:22 How to get started with open source?
*** 8:54: How is cloning a project different from forking?
*** 13:22 Interview with an active open source contributor, Bill Morrison

** Resources mentioned
Hackathon hackers 
A facebook group for people to share online content about the tech industry and spark related conversation
Github: 
A service that hosts code bases for software projects  and facilitates collaboration between software developers.
CodeTriage
A site that notifies you when an open source project that you're subscribed to has an open issue you can help resolve.
Outreachy
Outreachy pays remote interns to contribute to open source software.
Open Source Guide
A collection of guides for contributing to and launching open source projects
Hacktoberfest
A celebration of open source for the month of October. 5 open source contributions and you get a free T-shirt!
Jasper 
Easily track of active issues on your favourite open source projects. 
